### ISSUE TITLE
Implement warp zones as an option for mappers (and as an option for mods, like portal guns).

### ISSUE THREAD

**Issue by dGr8LookinSparky** [TheDushan/OpenWolf-Engine#1]
A must have from Xonotic, warpzones:

https://www.youtube.com/watch?v=lOrUJsg7DB8

code:

https://gitlab.com/xonotic/darkplaces/blob/div0-stable/client.h#L2016
https://gitlab.com/xonotic/darkplaces/blob/div0-stable/clvm_cmds.c#L4181
https://gitlab.com/xonotic/xonotic-data.pk3dir/tree/master/qcsrc/lib/warpzone
https://gitlab.com/search?utf8=%E2%9C%93&search=warpzone&group_id=&project_id=73440&search_code=true&repository_ref=master

**Comment by dGr8LookinSparky** [comment]
Another example video:

https://www.youtube.com/watch?v=ORh6NfQRDxg

**Comment by TheDushan** [comment]
I don't plan to add this, if someone is interested in this feature, please submit pull request.
